"""
Metadatos de catálogo (PA, presentación, forma) para productos faltantes.
Fuentes: PLM, probemedic, ficha técnica MX, codigo de barras en tiendas MX.
"""

from __future__ import annotations

# Campos por barcode:
#   nombre, marca, presentacion, principio_activo, concentracion,
#   forma_farmaceutica, categoria, tipo, requiere_receta
BARCODE_CATALOG: dict[str, dict] = {
    # ── XL-3 / Genomma antigripales ─────────────────────────────────────
    "650240017100": {
        "nombre": "XL-3 VR",
        "marca": "XL-3",
        "presentacion": "C/24",
        "principio_activo": "Paracetamol + Amantadina + Clorfenamina",
        "concentracion": "375/50/3 MG",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "6502400170941": {
        "nombre": "XL-3 Xtra",
        "marca": "XL-3",
        "presentacion": "C/12",
        "principio_activo": "Paracetamol + Fenilefrina + Clorfenamina",
        "concentracion": "",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "6502400525451": {
        "nombre": "XL-3 Tab",
        "marca": "XL-3",
        "presentacion": "C/10",
        "principio_activo": "Paracetamol + Fenilefrina + Clorfenamina",
        "concentracion": "",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "650240010538": {
        "nombre": "Next Tab",
        "marca": "Next",
        "presentacion": "C/10",
        "principio_activo": "Paracetamol + Fenilefrina + Clorfenamina",
        "concentracion": "",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "650240015366": {
        "nombre": "Nasalub Sol",
        "marca": "Nasalub",
        "presentacion": "30 ML",
        "principio_activo": "Cloruro de sodio + Glicerol",
        "concentracion": "",
        "forma_farmaceutica": "SPRAY",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "650240036354": {
        "nombre": "Genoprazol",
        "marca": "Genoprazol",
        "presentacion": "C/7",
        "principio_activo": "Omeprazol",
        "concentracion": "20 MG",
        "forma_farmaceutica": "CAPSULAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "6502400315021": {
        "nombre": "Tukol-D",
        "marca": "Tukol-D",
        "presentacion": "Jbe Inf",
        "principio_activo": "Guaifenesina + Dextrometorfano",
        "concentracion": "",
        "forma_farmaceutica": "JARABE",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "650240010712": {
        "nombre": "Tukol-D",
        "marca": "Tukol-D",
        "presentacion": "125 ML",
        "principio_activo": "Guaifenesina + Dextrometorfano",
        "concentracion": "",
        "forma_farmaceutica": "JARABE",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "65024000740024": {
        "nombre": "Silka Medic Gel",
        "marca": "Silka",
        "presentacion": "",
        "principio_activo": "Benzocaina + Mentol",
        "concentracion": "",
        "forma_farmaceutica": "GEL",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "650240006647": {
        "nombre": "Ultra Bengue",
        "marca": "Ultra Bengue",
        "presentacion": "Gel",
        "principio_activo": "Mentol + Alcanfor",
        "concentracion": "",
        "forma_farmaceutica": "GEL",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    # ── Vitacilina / tópicos KSK ────────────────────────────────────────
    "354312225164": {
        "nombre": "Vitacilina Bebé",
        "marca": "Vitacilina",
        "presentacion": "Pomada",
        "principio_activo": "Neomicina + Bacitracina zinc",
        "concentracion": "",
        "forma_farmaceutica": "POMADA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7502250343072": {
        "nombre": "Vitacilina 28",
        "marca": "Vitacilina",
        "presentacion": "Crema",
        "principio_activo": "Neomicina + Bacitracina zinc",
        "concentracion": "",
        "forma_farmaceutica": "CREMA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "750022503405381": {
        "nombre": "Vitacilina Ungüento",
        "marca": "Vitacilina",
        "presentacion": "",
        "principio_activo": "Neomicina + Bacitracina zinc",
        "concentracion": "",
        "forma_farmaceutica": "UNGÜENTO",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "3543122250276": {
        "nombre": "Derman Crema 50 g",
        "marca": "Derman",
        "presentacion": "50 G",
        "principio_activo": "Ácido undecilénico + Undecilenato de zinc",
        "concentracion": "18/5 G/100G",
        "forma_farmaceutica": "CREMA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    # Alias OCR (Tempra+Derman en misma línea FarmaLive)
    "7501354312225027": {
        "nombre": "Derman Crema 50 g",
        "marca": "Derman",
        "presentacion": "50 G",
        "principio_activo": "Ácido undecilénico + Undecilenato de zinc",
        "concentracion": "18/5 G/100G",
        "forma_farmaceutica": "CREMA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7501354312250": {
        "nombre": "Derman Crema 50 g",
        "marca": "Derman",
        "presentacion": "50 G",
        "principio_activo": "Ácido undecilénico + Undecilenato de zinc",
        "concentracion": "18/5 G/100G",
        "forma_farmaceutica": "CREMA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7501312250181": {
        "nombre": "Rocainol",
        "marca": "Rocainol",
        "presentacion": "45 G",
        "principio_activo": "Salicilato de metilo + Mentol",
        "concentracion": "16/8 G/100G",
        "forma_farmaceutica": "UNGÜENTO",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7501050613453": {
        "nombre": "Afrin Adulto spray",
        "marca": "Bayer",
        "presentacion": "20 mL",
        "principio_activo": "Oximetazolina clorhidrato",
        "concentracion": "0.05%",
        "forma_farmaceutica": "Solución nasal",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7501050624732": {
        "nombre": "Afrin No Drip extra humectante",
        "marca": "Bayer",
        "presentacion": "15 mL",
        "principio_activo": "Oximetazolina clorhidrato",
        "concentracion": "0.05%",
        "forma_farmaceutica": "Solución nasal",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    # ── RB / Bayer / Haleon ─────────────────────────────────────────────
    "75010954525051": {
        "nombre": "Tempra Forte",
        "marca": "Tempra",
        "presentacion": "C/24",
        "principio_activo": "Paracetamol",
        "concentracion": "500 MG",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "75012501050724298": {
        "nombre": "Tempra Jbe",
        "marca": "Tempra",
        "presentacion": "120 ML",
        "principio_activo": "Paracetamol",
        "concentracion": "",
        "forma_farmaceutica": "JARABE",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7501058715517": {
        "nombre": "Graneodin B",
        "marca": "Graneodin",
        "presentacion": "C/24",
        "principio_activo": "Benzocaina",
        "concentracion": "10 MG",
        "forma_farmaceutica": "PASTILLAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7501064560163": {
        "nombre": "Iodex Cristal",
        "marca": "Iodex",
        "presentacion": "60 G",
        "principio_activo": "Mentol + Eucalipto",
        "concentracion": "",
        "forma_farmaceutica": "UNGÜENTO",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7503050071598": {
        "nombre": "Theraflu TD",
        "marca": "Theraflu",
        "presentacion": "",
        "principio_activo": "Paracetamol + Fenilefrina + Feniramina",
        "concentracion": "",
        "forma_farmaceutica": "POLVO",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    # ── Otros medicamentos ──────────────────────────────────────────────
    "36647980596011": {
        "nombre": "Aderogyl",
        "marca": "Aderogyl",
        "presentacion": "Amp C/4",
        "principio_activo": "Vitamina C + Vitamina A + Vitamina D3 + Complejo B",
        "concentracion": "",
        "forma_farmaceutica": "AMPOLLETA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7501537182960": {
        "nombre": "Tribedoce 50000 UI Amp C/5",
        "marca": "Bruluart",
        "presentacion": "Amp C/5",
        "principio_activo": "Hidroxocobalamina + Tiamina + Piridoxina",
        "concentracion": "50000 UI / 100 mg / 50 mg",
        "forma_farmaceutica": "AMPOLLETA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
        "requiere_receta": True,
    },
    "75015015371829601": {
        "nombre": "Tribedoce 50000 UI Amp C/5",
        "marca": "Bruluart",
        "presentacion": "Amp C/5",
        "principio_activo": "Hidroxocobalamina + Tiamina + Piridoxina",
        "concentracion": "50000 UI / 100 mg / 50 mg",
        "forma_farmaceutica": "AMPOLLETA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
        "requiere_receta": True,
    },
    "7501501537161": {
        "nombre": "Tribedoce 50000 UI Amp C/5",
        "marca": "Bruluart",
        "presentacion": "Amp C/5",
        "principio_activo": "Hidroxocobalamina + Tiamina + Piridoxina",
        "concentracion": "50000 UI / 100 mg / 50 mg",
        "forma_farmaceutica": "AMPOLLETA",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
        "requiere_receta": True,
    },
    "7501537164713": {
        "nombre": "Tribedoce Compuesto grageas C/30",
        "marca": "Bruluart",
        "presentacion": "C/30 grageas",
        "principio_activo": "Diclofenaco + Complejo B (Tiamina, Piridoxina, Cianocobalamina)",
        "concentracion": "50/50/1/50 mg",
        "forma_farmaceutica": "GRAGEAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
        "requiere_receta": True,
    },
    "7501537163266": {
        "nombre": "Tribedoce Compuesto Amp C/3",
        "marca": "Bruluart",
        "presentacion": "Amp C/3",
        "principio_activo": "Diclofenaco + Complejo B (Tiamina, Piridoxina, Cianocobalamina)",
        "concentracion": "75/5/100 mg",
        "forma_farmaceutica": "SOLUCION INYECTABLE",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
        "requiere_receta": True,
    },
    "7507201092730451": {
        "nombre": "Riopan Sobres",
        "marca": "Riopan",
        "presentacion": "Sobres",
        "principio_activo": "Magaldrato",
        "concentracion": "",
        "forma_farmaceutica": "SOBRES",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "75029650608272": {
        "nombre": "Contac Ultra",
        "marca": "Contac",
        "presentacion": "",
        "principio_activo": "Paracetamol + Fenilefrina + Clorfenamina",
        "concentracion": "",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7503854221482": {
        "nombre": "Deeflamox Plus",
        "marca": "Deeflamox",
        "presentacion": "",
        "principio_activo": "Amoxicilina + Acido clavulanico",
        "concentracion": "875/125 MG",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
        "requiere_receta": True,
    },
    "750525301508201": {
        "nombre": "Antiflu-Des",
        "marca": "Antiflu-Des",
        "presentacion": "",
        "principio_activo": "Paracetamol + Clorfenamina + Fenilefrina",
        "concentracion": "",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7501210734092301": {
        "nombre": "Syncol Max",
        "marca": "Syncol Max",
        "presentacion": "",
        "principio_activo": "Naproxeno + Paracetamol",
        "concentracion": "",
        "forma_farmaceutica": "TABLETAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "780083146207": {
        "nombre": "Fazolin F",
        "marca": "Fazolin",
        "presentacion": "15 ML",
        "principio_activo": "Nafazolina",
        "concentracion": "",
        "forma_farmaceutica": "GOTAS",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    "7509854054221": {
        "nombre": "Splash Tears",
        "marca": "Splash Tears",
        "presentacion": "Sol oftálmica",
        "principio_activo": "Hipromelosa",
        "concentracion": "",
        "forma_farmaceutica": "SOLUCION",
        "categoria": "Medicamentos",
        "tipo": "MEDICAMENTO",
    },
    # ── Higiene / abarrotes ───────────────────────────────────────────
    "7501685171113": {
        "nombre": "Condón Sico Invisible",
        "marca": "Sico",
        "presentacion": "C/3",
        "principio_activo": "",
        "concentracion": "",
        "forma_farmaceutica": "CONDON",
        "categoria": "Higiene",
        "tipo": "GENERICO",
    },
    "7501058367129": {
        "nombre": "Condón Sico Negro Feel",
        "marca": "Sico",
        "presentacion": "C/3",
        "principio_activo": "",
        "concentracion": "",
        "forma_farmaceutica": "CONDON",
        "categoria": "Higiene",
        "tipo": "GENERICO",
    },
    "75010583683367": {
        "nombre": "Condón Sico Rojo Feel",
        "marca": "Sico",
        "presentacion": "C/3",
        "principio_activo": "",
        "concentracion": "",
        "forma_farmaceutica": "CONDON",
        "categoria": "Higiene",
        "tipo": "GENERICO",
    },
    "7501033954245": {
        "nombre": "Pediasure",
        "marca": "Pediasure",
        "presentacion": "236 ML",
        "principio_activo": "Suplemento nutricional",
        "concentracion": "",
        "forma_farmaceutica": "LIQUIDO",
        "categoria": "Abarrotes",
        "tipo": "GENERICO",
    },
    "7501054558682": {
        "nombre": "Nivea Milk",
        "marca": "Nivea",
        "presentacion": "400 ML",
        "principio_activo": "",
        "concentracion": "",
        "forma_farmaceutica": "CREMA",
        "categoria": "Cuidado personal",
        "tipo": "GENERICO",
    },
}

# Suerox — misma base, distinto sabor
_SUEROX_BASE = {
    "nombre": "Suerox",
    "marca": "Suerox",
    "principio_activo": "Electrolitos / Suero oral",
    "concentracion": "",
    "forma_farmaceutica": "BEBIDA",
    "categoria": "Abarrotes",
    "tipo": "GENERICO",
}
_SUEROX_FLAVORS: dict[str, str] = {
    "6502400322571": "Manzana 630 ML",
    "6502400323011": "Naranja Mandarina 630 ML",
    "6502400721471": "Naranja Mango 630 ML",
    "6502400721541": "Manzana V-Limón 630 ML",
    "650240074455": "Uva Mora Azul 630 ML",
    "6502400661391": "Frutos Rojos 630 ML",
    "650240066306": "Fresa 630 ML",
    "650240032264": "Eresa-Kiwi 630 ML",
    "650240032271": "Uva 630 ML",
    "650240032295": "Mora Azul 630 ML",
    "650240032325": "Lima Limón 630 ML",
    "650240035395": "Coco 630 ML",
    "6502400744481": "Coco Piña 630 ML",
}
for _bc, _pres in _SUEROX_FLAVORS.items():
    BARCODE_CATALOG[_bc] = {**_SUEROX_BASE, "presentacion": _pres}

# OTC / abarrotes frecuentes en inventario (barcode → PA + presentación)
_OTC_ENTRIES: dict[str, dict] = {
    "7501008443026": {
        "marca": "Alka-Seltzer",
        "principio_activo": "Acido acetilsalicilico + Acido citrico + Bicarbonato de sodio",
        "forma_farmaceutica": "TABLETAS EFERVESCENTES",
    },
    "75010084999001": {
        "marca": "Alka-Seltzer",
        "principio_activo": "Acido acetilsalicilico + Acido citrico + Bicarbonato de sodio",
        "forma_farmaceutica": "TABLETAS EFERVESCENTES",
    },
    "7501008491096": {
        "marca": "Cafiaspirina",
        "principio_activo": "Acido acetilsalicilico + Caffeina",
        "forma_farmaceutica": "TABLETAS",
    },
    "7501008496701": {
        "marca": "Aspirina",
        "principio_activo": "Acido acetilsalicilico",
        "forma_farmaceutica": "TABLETAS EFERVESCENTES",
    },
    "7501008491074": {
        "marca": "Aspirina",
        "principio_activo": "Acido acetilsalicilico",
        "forma_farmaceutica": "TABLETAS",
    },
    "7502208895196": {
        "marca": "Aspirina",
        "principio_activo": "Acido acetilsalicilico",
        "forma_farmaceutica": "TABLETAS",
    },
    "75010084335531": {
        "marca": "Aspirina",
        "principio_activo": "Acido acetilsalicilico + Caffeina",
        "forma_farmaceutica": "TABLETAS",
    },
    "75916565": {
        "marca": "Vicks",
        "principio_activo": "Alcanfor + Mentol + Eucalipto",
        "forma_farmaceutica": "POMADA",
    },
    "7590002012475": {
        "marca": "Vicks",
        "principio_activo": "Alcanfor + Mentol + Eucalipto",
        "forma_farmaceutica": "UNGÜENTO",
    },
    "7590002012468": {
        "marca": "Vicks",
        "principio_activo": "Alcanfor + Mentol + Eucalipto",
        "forma_farmaceutica": "UNGÜENTO",
    },
    "7503003406501": {
        "marca": "Quirmex",
        "principio_activo": "Vaselina + Lanolina",
        "forma_farmaceutica": "POMADA",
    },
    "7503003406600": {
        "marca": "Quirmex",
        "principio_activo": "Vaselina + Lanolina",
        "forma_farmaceutica": "POMADA",
    },
    "7506552900322": {
        "marca": "Quirmex",
        "principio_activo": "Vaselina + Lanolina",
        "forma_farmaceutica": "POMADA",
    },
    "75030034063651": {
        "marca": "Quirmex",
        "principio_activo": "Vaselina + Lanolina",
        "forma_farmaceutica": "POMADA",
    },
    "75030034067301": {
        "marca": "Quirmex",
        "principio_activo": "Vaselina + Lanolina",
        "forma_farmaceutica": "POMADA",
    },
    "7501065095718": {
        "marca": "Centrum",
        "principio_activo": "Multivitaminico + Minerales",
        "forma_farmaceutica": "TABLETAS",
    },
    "7501065095947": {
        "marca": "Centrum",
        "principio_activo": "Multivitaminico + Minerales",
        "forma_farmaceutica": "TABLETAS",
    },
    "75010650959781": {
        "marca": "Centrum",
        "principio_activo": "Multivitaminico + Minerales",
        "forma_farmaceutica": "TABLETAS",
    },
    "7503008344488": {
        "marca": "Lactopram",
        "principio_activo": "Lactobacillus acidophilus",
        "forma_farmaceutica": "CAPSULAS",
    },
    "7501125104268": {
        "marca": "Electrolit",
        "principio_activo": "Electrolitos / Suero oral",
        "forma_farmaceutica": "BEBIDA",
    },
    "7501125104411": {
        "marca": "Electrolit",
        "principio_activo": "Electrolitos / Suero oral",
        "forma_farmaceutica": "BEBIDA",
    },
    "7501125149221": {
        "marca": "Electrolit",
        "principio_activo": "Electrolitos / Suero oral",
        "forma_farmaceutica": "BEBIDA",
    },
    "75011251448511": {
        "marca": "Electrolit",
        "principio_activo": "Electrolitos / Suero oral",
        "forma_farmaceutica": "BEBIDA",
    },
    "75011251747971": {
        "marca": "Electrolit",
        "principio_activo": "Electrolitos / Suero oral",
        "forma_farmaceutica": "BEBIDA",
    },
    "75064560163": {
        "marca": "Iodex",
        "principio_activo": "Mentol + Eucalipto",
        "forma_farmaceutica": "UNGÜENTO",
    },
}
for _bc, _meta in _OTC_ENTRIES.items():
    BARCODE_CATALOG.setdefault(_bc, {**_meta, "presentacion": _meta.get("presentacion", "")})


def lookup_barcode_catalog(barcode: str | None) -> dict | None:
    """Busca metadatos por barcode exacto o truncado (BD a veces guarda EAN corto)."""
    bc = (barcode or "").strip()
    if not bc:
        return None
    if bc in BARCODE_CATALOG:
        return dict(BARCODE_CATALOG[bc])
    for cat_bc, meta in BARCODE_CATALOG.items():
        if cat_bc.endswith(bc) or bc.endswith(cat_bc[-8:]):
            return dict(meta)
    return None
