#!/usr/bin/env python3
"""Genera CSV del ticket Cityfarma 6315912 y el SQL de carga al inventario."""
from __future__ import annotations

import csv
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_TICKET = ROOT / "sql" / "generated" / "ticket_cityfarma_6315912.csv"
OUT_IMPORT = ROOT / "sql" / "generated" / "import_inventario_cityfarma_6315912.csv"
OUT_SQL = ROOT / "sql" / "patch_carga_cityfarma_6315912.sql"

FOLIO = "6315912"
PROVEEDOR = "Cityfarma Iztapalapa"
FECHA = "2026-08-21"


def ceil_pvp(costo: float, factor: float) -> float:
    return float(math.ceil(costo * factor))


# Ticket leído 21-ago-2026. P.U. = costo de compra (IVA ya en el renglón).
# match: sku/nombre/pvp/stock_min/cat existentes. None = alta.
ROWS = [
    {
        "linea": 1,
        "ean": "7501050613453",
        "desc_ticket": "AFRIN ADUL SPRAY",
        "qty": 2,
        "pu": 75.38,
        "subtotal": 150.76,
        "lote": "2601928",
        "match": True,
        "sku": "FC-06134531",
        "nombre": "Afrin Adulto spray 20 mL",
        "categoria": "Respiratorio",
        "tipo": "marca",
        "precio": 120.74,
        "stock_minimo": 5,
        "marca": "Afrin",
        "presentacion": "Spray 20 mL",
        "principio": "Oximetazolina",
        "concentracion": "",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO} · ya existía",
    },
    {
        "linea": 2,
        "ean": "7501050623766",
        "desc_ticket": "AFRIN NO DRIP SOL 15",
        "qty": 2,
        "pu": 115.52,
        "subtotal": 231.04,
        "lote": "2601390",
        "match": False,
        "sku": "FC-05062376",
        "nombre": "Afrin No Drip solución nasal 15 mL",
        "categoria": "Respiratorio",
        "tipo": "marca",
        "precio": ceil_pvp(115.52, 1.6),
        "stock_minimo": 2,
        "marca": "Afrin",
        "presentacion": "Solución 15 mL",
        "principio": "Oximetazolina",
        "concentracion": "",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO} · distinto de Afrin No Drip spray 7501050624732",
    },
    {
        "linea": 3,
        "ean": "7501165001725",
        "desc_ticket": "ALLEGRA 180 MG C 10",
        "qty": 1,
        "pu": 362.97,
        "subtotal": 362.97,
        "lote": "GMX0303",
        "match": False,
        "sku": "FC-16500172",
        "nombre": "Allegra fexofenadina 180 mg C/10",
        "categoria": "Alergia",
        "tipo": "marca",
        "precio": ceil_pvp(362.97, 1.2),
        "stock_minimo": 2,
        "marca": "Allegra",
        "presentacion": "Caja con 10 tabletas",
        "principio": "Fexofenadina",
        "concentracion": "180 mg",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO} · costo cerca de menudeo, margen 20%",
    },
    {
        "linea": 4,
        "ean": "7501065001337",
        "desc_ticket": "CALTRATE 600 D C30 T",
        "qty": 2,
        "pu": 153.59,
        "subtotal": 307.18,
        "lote": "T75M",
        "match": False,
        "sku": "FC-06500133",
        "nombre": "Caltrate 600 + D C/30",
        "categoria": "Vitaminas",
        "tipo": "marca",
        "precio": ceil_pvp(153.59, 1.6),
        "stock_minimo": 2,
        "marca": "Caltrate",
        "presentacion": "Caja con 30 tabletas",
        "principio": "Carbonato de calcio + vitamina D",
        "concentracion": "600 mg",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO}",
    },
    {
        "linea": 5,
        "ean": "7502276040368",
        "desc_ticket": "DESENFRIOL D C30 TAB",
        "qty": 3,
        "pu": 61.68,
        "subtotal": 185.04,
        "lote": "2601928",
        "match": True,
        "sku": "FC-60403681",
        "nombre": "Desenfriol D",
        "categoria": "Respiratorio",
        "tipo": "marca",
        "precio": 86.0,
        "stock_minimo": 5,
        "marca": "Desenfriol",
        "presentacion": "C/30",
        "principio": "Clorfenamina/Fenilefrina/Paracetamol",
        "concentracion": "",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO} · lote igual al de Afrin Adulto: confirmar en caja",
    },
    {
        "linea": 6,
        "ean": "7502276040405",
        "desc_ticket": "DESENFRIOLITO PLUS C",
        "qty": 2,
        "pu": 57.76,
        "subtotal": 115.52,
        "lote": "X26RXS",
        "match": True,
        "sku": "FC-76040610",
        "nombre": "Desenfriolito Plus Masticables",
        "categoria": "Analgésico",
        "tipo": "marca",
        "precio": ceil_pvp(57.76, 1.6),
        "stock_minimo": 5,
        "marca": "Bayer",
        "presentacion": "C/24 1 mg/2.5 mg/80 mg",
        "principio": "Clorfenamina/Fenilefrina/Paracetamol",
        "concentracion": "",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO} · costo subió; PVP 63→93 para no vender a 8%",
    },
    {
        "linea": 7,
        "ean": "7501300421524",
        "desc_ticket": "DOLAC 10MG C10 CAPS",
        "qty": 3,
        "pu": 99.73,
        "subtotal": 299.19,
        "lote": "T0623",
        "match": False,
        "sku": "FC-30042152",
        "nombre": "Dolac ketorolaco 10 mg C/10 cápsulas",
        "categoria": "Analgésico",
        "tipo": "marca",
        "precio": ceil_pvp(99.73, 1.6),
        "stock_minimo": 2,
        "marca": "Dolac",
        "presentacion": "Caja con 10 cápsulas",
        "principio": "Ketorolaco",
        "concentracion": "10 mg",
        "receta": True,
        "notas": f"Ticket Cityfarma {FOLIO} · receta. Distinto de ketorolaco genérico AMSA/Maver",
    },
    {
        "linea": 8,
        "ean": "3664798074680",
        "desc_ticket": "ENTEROGERMINA 2 BILL",
        "qty": 1,
        "pu": 200.00,
        "subtotal": 200.00,
        "lote": "6I086",
        "match": False,
        "sku": "FC-79807468",
        "nombre": "Enterogermina 2 billones C/10",
        "categoria": "Gastro",
        "tipo": "marca",
        "precio": ceil_pvp(200.00, 1.6),
        "stock_minimo": 2,
        "marca": "Enterogermina",
        "presentacion": "Caja con 10 frascos 5 mL",
        "principio": "Bacillus clausii",
        "concentracion": "2 billones",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO}",
    },
    {
        "linea": 9,
        "ean": "7501289511421",
        "desc_ticket": "PASTA LASSAR 30GR TA",
        "qty": 2,
        "pu": 22.50,
        "subtotal": 45.00,
        "lote": "26PL029",
        "match": True,
        "sku": "FC-9511421",
        "nombre": "Pasta Lassar Andromaco 30 g",
        "categoria": "Botiquín",
        "tipo": "marca",
        "precio": 31.89,
        "stock_minimo": 2,
        "marca": "Andromaco",
        "presentacion": "Frasco 30 g",
        "principio": "Óxido de zinc 25%",
        "concentracion": "",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO} · stock estaba en 0",
    },
    {
        "linea": 10,
        "ean": "7501289511414",
        "desc_ticket": "PASTA LASSAR 60GR TA",
        "qty": 2,
        "pu": 47.37,
        "subtotal": 94.74,
        "lote": "26PL057",
        "match": False,
        "sku": "FC-28951141",
        "nombre": "Pasta Lassar Andromaco 60 g",
        "categoria": "Botiquín",
        "tipo": "marca",
        "precio": ceil_pvp(47.37, 1.6),
        "stock_minimo": 2,
        "marca": "Andromaco",
        "presentacion": "Frasco 60 g",
        "principio": "Óxido de zinc 25%",
        "concentracion": "",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO} · distinta de la de 30 g",
    },
    {
        "linea": 11,
        "ean": "4001895928765",
        "desc_ticket": "TEGADERM 10X12CM C50",
        "qty": 1,
        "pu": 579.55,
        "subtotal": 579.55,
        "lote": "344JWY",
        "match": False,
        "sku": "FC-89592876",
        "nombre": "Tegaderm 3M 10 x 12 cm C/50",
        "categoria": "Dispositivo médico",
        "tipo": "marca",
        "precio": ceil_pvp(579.55, 1.2),
        "stock_minimo": 1,
        "marca": "Tegaderm",
        "presentacion": "Caja con 50 apósitos 10 x 12 cm",
        "principio": "",
        "concentracion": "",
        "receta": False,
        "notas": f"Ticket Cityfarma {FOLIO} · caja C/50. Costo alto, margen 20%",
    },
]


def sql_str(v: str | None) -> str:
    if v is None:
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def sql_bool(v: bool) -> str:
    return "true" if v else "false"


def write_ticket_csv() -> None:
    OUT_TICKET.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "linea", "folio", "fecha", "proveedor", "ean", "descripcion_ticket",
        "cantidad", "precio_unitario", "subtotal", "lote", "caducidad",
        "sku_farmacapital", "accion",
    ]
    with OUT_TICKET.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in ROWS:
            w.writerow({
                "linea": r["linea"],
                "folio": FOLIO,
                "fecha": FECHA,
                "proveedor": PROVEEDOR,
                "ean": r["ean"],
                "descripcion_ticket": r["desc_ticket"],
                "cantidad": r["qty"],
                "precio_unitario": f"{r['pu']:.2f}",
                "subtotal": f"{r['subtotal']:.2f}",
                "lote": r["lote"],
                "caducidad": "",
                "sku_farmacapital": r["sku"],
                "accion": "recibir" if r["match"] else "alta",
            })


def write_import_csv() -> None:
    fields = [
        "SKU", "Codigo_Barras", "Nombre", "Categoria", "Tipo", "Stock", "Stock_Minimo",
        "Precio_Venta", "Costo", "Proveedor", "Lote", "Fecha_Caducidad",
        "Descuento_Porcentaje",
        "Marca_Comercial", "Principio_Activo", "Concentracion", "Presentacion",
        "Contenido_Caja", "Linea_Comercial", "Grupo_Farmacologico", "Jerarquia",
        "SKU_Casa_Saba", "Stock_Maximo", "Notas",
    ]
    with OUT_IMPORT.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, quoting=csv.QUOTE_ALL)
        w.writeheader()
        for r in ROWS:
            w.writerow({
                "SKU": r["sku"],
                "Codigo_Barras": r["ean"],
                "Nombre": r["nombre"],
                "Categoria": r["categoria"],
                "Tipo": r["tipo"],
                "Stock": r["qty"],
                "Stock_Minimo": r["stock_minimo"],
                "Precio_Venta": f"{r['precio']:.2f}",
                "Costo": f"{r['pu']:.2f}",
                "Proveedor": PROVEEDOR,
                "Lote": r["lote"],
                "Fecha_Caducidad": "",
                "Descuento_Porcentaje": "0",
                "Marca_Comercial": r["marca"],
                "Principio_Activo": r["principio"],
                "Concentracion": r["concentracion"],
                "Presentacion": r["presentacion"],
                "Contenido_Caja": "",
                "Linea_Comercial": "",
                "Grupo_Farmacologico": "",
                "Jerarquia": "",
                "SKU_Casa_Saba": "",
                "Stock_Maximo": "",
                "Notas": r["notas"],
            })


def write_sql() -> None:
    lines = [
        "-- Cityfarma Iztapalapa · venta 6315912 · 21-ago-2026 09:15",
        "-- Comercializadora Yalesa / Cityfarma · PAGADO",
        "-- 11 renglones · suma P.U.×qty = $2,570.99 (el ticket parte IVA $79.94 ya va en el P.U.)",
        "-- El ticket no trae caducidad: los lotes entran sin fecha; captúrala en Lotes al abrir la caja.",
        "--",
        "-- ADDITIVO: suma stock. No borra lotes viejos (Afrin Adulto ya tiene 20 pzas).",
        "-- Idempotente: si ya existe el mismo numero_lote en ese producto, no vuelve a recibir.",
        "-- 4 ya estaban · 7 altas. Afrin No Drip SOL 15 ≠ spray 7501050624732.",
        "--",
        "-- Elige UNA vía: este SQL **o** Importar CSV. No las dos.",
        "-- Ejecutar en Supabase SQL Editor (archivo completo).",
        "-- proveedor no existe en productos: se guarda en lotes.proveedor_id.",
        "",
        "begin;",
        "",
        "create temp table _fc_cf6315912 (",
        "  linea integer,",
        "  ean text primary key,",
        "  sku text not null,",
        "  nombre text not null,",
        "  categoria text not null,",
        "  tipo text not null,",
        "  qty integer not null,",
        "  costo numeric(12,2) not null,",
        "  precio numeric(12,2) not null,",
        "  stock_minimo integer not null,",
        "  lote text not null,",
        "  marca text,",
        "  presentacion text,",
        "  principio_activo text,",
        "  concentracion text,",
        "  requiere_receta boolean not null default false,",
        "  notas text,",
        "  es_alta boolean not null",
        ") on commit drop;",
        "",
        "insert into _fc_cf6315912 values",
    ]
    vals = []
    for r in ROWS:
        vals.append(
            "  ({linea}, {ean}, {sku}, {nombre}, {cat}, {tipo}, {qty}, {costo}, {precio}, {smin}, {lote}, {marca}, {pres}, {pa}, {conc}, {receta}, {notas}, {alta})".format(
                linea=r["linea"],
                ean=sql_str(r["ean"]),
                sku=sql_str(r["sku"]),
                nombre=sql_str(r["nombre"]),
                cat=sql_str(r["categoria"]),
                tipo=sql_str(r["tipo"]),
                qty=r["qty"],
                costo=f"{r['pu']:.2f}",
                precio=f"{r['precio']:.2f}",
                smin=r["stock_minimo"],
                lote=sql_str(r["lote"]),
                marca=sql_str(r["marca"]),
                pres=sql_str(r["presentacion"]),
                pa=sql_str(r["principio"] or None),
                conc=sql_str(r["concentracion"] or None),
                receta=sql_bool(r["receta"]),
                notas=sql_str(r["notas"]),
                alta="true" if not r["match"] else "false",
            )
        )
    lines.append(",\n".join(vals) + ";")
    lines += [
        "",
        "do $$",
        "declare",
        "  r record;",
        "  v_pid bigint;",
        "  v_lid bigint;",
        "  n_alta integer := 0;",
        "  n_recv integer := 0;",
        "  n_skip integer := 0;",
        "begin",
        "  for r in select * from _fc_cf6315912 order by linea loop",
        "    select p.id into v_pid",
        "    from public.productos p",
        "    where p.codigo_barras = r.ean or p.sku = r.sku",
        "    order by case when p.codigo_barras = r.ean then 0 else 1 end, p.id",
        "    limit 1;",
        "",
        "    if v_pid is null then",
        "      select f.producto_id into v_pid",
        "      from public.create_producto_with_lote(",
        "        jsonb_build_object(",
        "          'nombre', r.nombre,",
        "          'sku', r.sku,",
        "          'codigo_barras', r.ean,",
        "          'categoria', r.categoria,",
        "          'tipo', r.tipo,",
        "          'descripcion', r.notas,",
        "          'costo', r.costo,",
        "          'precio', r.precio,",
        "          'stock_minimo', r.stock_minimo,",
        "          'activo', true,",
        "          'requiere_receta', r.requiere_receta",
        "        ),",
        "        0,",
        "        null,",
        "        null::date,",
        "        r.costo,",
        "        null::bigint",
        "      ) f;"
        "      n_alta := n_alta + 1;",
        "    else",
        "      update public.productos set",
        "        costo = r.costo,",
        "        precio = r.precio,",
        "        stock_minimo = r.stock_minimo",
        "      where id = v_pid;",
        "    end if;",
        "",
        "    update public.productos set",
        "      marca = r.marca,",
        "      presentacion = r.presentacion,",
        "      principio_activo = coalesce(r.principio_activo, principio_activo),",
        "      concentracion = coalesce(r.concentracion, concentracion),",
        "      categoria = r.categoria",
        "    where id = v_pid;",
        "  end loop;",
        "",
        "  raise notice 'Cityfarma 6315912: % altas, % recepciones, % lotes ya existian', n_alta, n_recv, n_skip;",
        "end $$;",
        "",
        "select",
        "  t.linea,",
        "  t.sku,",
        "  t.ean,",
        "  left(t.nombre, 42) as nombre,",
        "  t.qty as pzas_ticket,",
        "  p.stock as stock_bd,",
        "  t.costo as costo_ticket,",
        "  p.costo as costo_bd,",
        "  t.precio as pvp,",
        "  p.precio as pvp_bd,",
        "  l.numero_lote,",
        "  l.cantidad_actual as lote_qty,",
        "  case",
        "    when p.id is null then 'SIN PRODUCTO'",
        "    when l.id is null then 'SIN LOTE'",
        "    else 'OK'",
        "  end as estado",
        "from _fc_cf6315912 t",
        "left join public.productos p on p.codigo_barras = t.ean or p.sku = t.sku",
        "left join lateral (",
        "  select l.* from public.lotes l",
        "  where l.producto_id = p.id and l.numero_lote = t.lote and coalesce(l.activo, true)",
        "  order by l.id desc",
        "  limit 1",
        ") l on true",
        "order by t.linea;",
        "",
        "commit;",
        "",
    ]
    OUT_SQL.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    write_ticket_csv()
    write_import_csv()
    write_sql()
    total = sum(r["subtotal"] for r in ROWS)
    print(f"ticket  {OUT_TICKET}")
    print(f"import  {OUT_IMPORT}")
    print(f"sql     {OUT_SQL}")
    print(f"lineas {len(ROWS)}  total ${total:.2f}")
    print(f"altas {sum(1 for r in ROWS if not r['match'])}  recibir {sum(1 for r in ROWS if r['match'])}")
