-- Tabla para banners editables desde Admin → Banners (tienda web).
-- Ejecutar en Supabase SQL Editor si aún no existe.

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  titulo text not null,
  subtitulo text,
  descripcion text,
  emoji text default '💊',
  bg text,
  cta text default 'Ver más',
  pagina text default 'catalogo',
  orden int default 0,
  activo boolean default true,
  slot text default 'hero',
  created_at timestamptz default now()
);

-- slot: hero (carrusel) | strip (franja debajo de badges) | tile (mosaico bajo búsqueda)

alter table public.banners enable row level security;

-- Políticas: lectura pública de activos (tienda); escritura solo service role o según tu modelo.
-- Ajustá según tu setup de Supabase Auth.
