-- Renombrar productos con nombres truncados / OCR ilegibles
-- 113 updates · solo campo nombre · 2026-08-14
-- NO modifica precio, costo, stock ni presentación

BEGIN;

UPDATE public.productos SET nombre = 'Clamoxin 12H (Amoxicilina/Clavulánico)' WHERE sku = 'FC-F22C72BE' AND activo = true;
UPDATE public.productos SET nombre = 'Clamoxin 12H Jr (Amoxicilina/Clavulánico susp.)' WHERE sku = 'FC-516C2E89' AND activo = true;
UPDATE public.productos SET nombre = 'Clamoxin 12H Ped (Amoxicilina/Clavulánico susp.)' WHERE sku = 'FC-DDFBABDF' AND activo = true;
UPDATE public.productos SET nombre = 'Acetona Jaloma chico' WHERE sku = 'FC-84431050' AND activo = true;
UPDATE public.productos SET nombre = 'Acetona Jaloma mediano' WHERE sku = 'FC-84437151' AND activo = true;
UPDATE public.productos SET nombre = 'Ampigrin AD (Ampicilina + Dicloxacilina)' WHERE sku = 'FC-2001A890' AND activo = true;
UPDATE public.productos SET nombre = 'Afrin DTC rojo spray' WHERE sku = 'FC-06134531' AND activo = true;
UPDATE public.productos SET nombre = 'Afrin No Drip extra humectante spray' WHERE sku = 'FC-06247327' AND activo = true;
UPDATE public.productos SET nombre = 'Agrifen AB polvo efervescente' WHERE sku = 'FC-25116810' AND activo = true;
UPDATE public.productos SET nombre = 'Ajolotius menta eucalipto sin azúcar pastillas' WHERE sku = 'FC-52400038' AND activo = true;
UPDATE public.productos SET nombre = 'Blumen coconut líquido' WHERE sku = 'FC-67905186' AND activo = true;
UPDATE public.productos SET nombre = 'Blumen jabón líquido cherry blossom' WHERE sku = 'FC-67905131' AND activo = true;
UPDATE public.productos SET nombre = 'Charlyn (Ciprofloxacino)' WHERE sku = 'FC-7AF7ACB5' AND activo = true;
UPDATE public.productos SET nombre = 'Chinoin Junior jarabe infantil' WHERE sku = 'FC-85097661' AND activo = true;
UPDATE public.productos SET nombre = 'Cina (Ciprofloxacino)' WHERE sku = 'FC-B25B4654' AND activo = true;
UPDATE public.productos SET nombre = 'Clamoxin (Amoxicilina/Clavulánico susp. 250/62.5)' WHERE sku = 'FC-F48FF7EF' AND activo = true;
UPDATE public.productos SET nombre = 'Clamoxin (Amoxicilina/Clavulánico 500/125 mg)' WHERE sku = 'FC-5F30F9D4' AND activo = true;
UPDATE public.productos SET nombre = 'Clamoxin (Amoxicilina/Clavulánico 500/125 mg)' WHERE sku = 'FC-6519183A' AND activo = true;
UPDATE public.productos SET nombre = 'Claris toallas desmaquillantes aloe C/40' WHERE sku = 'FC-21012303' AND activo = true;
UPDATE public.productos SET nombre = 'Crema Grisi aloe vera para manos' WHERE sku = 'FC-20501765' AND activo = true;
UPDATE public.productos SET nombre = 'Crema Grisi concha nácar para manos' WHERE sku = 'FC-36040450' AND activo = true;
UPDATE public.productos SET nombre = 'Crema Hinds hidratación extra almendras' WHERE sku = 'FC-36041402' AND activo = true;
UPDATE public.productos SET nombre = 'Crema Hinds líquida agave azul' WHERE sku = 'FC-20501673' AND activo = true;
UPDATE public.productos SET nombre = 'Crema Lubriderm piel normal' WHERE sku = 'FC-31244486' AND activo = true;
UPDATE public.productos SET nombre = 'Crema para peinar Pert aceite oliva aguacate' WHERE sku = 'FC-20500171' AND activo = true;
UPDATE public.productos SET nombre = 'Dac (Paracetamol + Diclofenaco)' WHERE sku = 'FC-1FFBB505' AND activo = true;
UPDATE public.productos SET nombre = 'Dermodine infantil' WHERE sku = 'FC-08820243' AND activo = true;
UPDATE public.productos SET nombre = 'Desodorante Ego Force 24H roll-on' WHERE sku = 'FC-75064938' AND activo = true;
UPDATE public.productos SET nombre = 'Dison Dex' WHERE sku = 'FC-1CF27DC9' AND activo = true;
UPDATE public.productos SET nombre = 'Hierro Dex' WHERE sku = 'FC-2E79C2D8' AND activo = true;
UPDATE public.productos SET nombre = 'Dibar algodón grande' WHERE sku = 'FC-68910034' AND activo = true;
UPDATE public.productos SET nombre = 'Eferox (Cefalexina)' WHERE sku = 'FC-DB4A39AE' AND activo = true;
UPDATE public.productos SET nombre = 'Escudo jabón líquido blanco neutro' WHERE sku = 'FC-43489165' AND activo = true;
UPDATE public.productos SET nombre = 'Bactiver F (Sulfametoxazol/Trimetoprima)' WHERE sku = 'FC-F8691496' AND activo = true;
UPDATE public.productos SET nombre = 'Fazolin F (nafazolina)' WHERE sku = 'FC-83146207' AND activo = true;
UPDATE public.productos SET nombre = 'FC producto botiquín' WHERE sku = 'FC-C8B741F6' AND activo = true;
UPDATE public.productos SET nombre = 'Graneodin B (benzocaína)' WHERE sku = 'FC-58715517' AND activo = true;
UPDATE public.productos SET nombre = 'Graneodin F (flurbiprofeno)' WHERE sku = 'FC-87154871' AND activo = true;
UPDATE public.productos SET nombre = 'Histiacil NF adulto jarabe' WHERE sku = 'FC-28979502' AND activo = true;
UPDATE public.productos SET nombre = 'Amcef IM 1 g (Inyectable)' WHERE sku = 'FC-BE76D409' AND activo = true;
UPDATE public.productos SET nombre = 'Ceftriaxona IM 1 g (Inyectable)' WHERE sku = 'FC-C636D8EA' AND activo = true;
UPDATE public.productos SET nombre = 'Amcef IM 500 mg (Inyectable)' WHERE sku = 'FC-07F04F88' AND activo = true;
UPDATE public.productos SET nombre = 'Cefotaxima IM (Inyectable)' WHERE sku = 'FC-22B18244' AND activo = true;
UPDATE public.productos SET nombre = 'Infamid (Metamizol + Dexametasona + Vit. B)' WHERE sku = 'FC-DE106642' AND activo = true;
UPDATE public.productos SET nombre = 'Iri (Inmunoglobulina)' WHERE sku = 'FC-30133021' AND activo = true;
UPDATE public.productos SET nombre = 'Lásico pomada' WHERE sku = 'FC-54504870' AND activo = true;
UPDATE public.productos SET nombre = 'Madrid Aceite Eucalipto' WHERE sku = 'FC-E69F2E63' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Aceite Almendras' WHERE sku = 'FC-D4AC123B' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Aceite Coco' WHERE sku = 'FC-931B4809' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Aceite Gomenolado' WHERE sku = 'FC-69387811' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Aceite Olivo' WHERE sku = 'FC-5A697CC2' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Aceite Romero' WHERE sku = 'FC-38CAFE6B' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Arnica' WHERE sku = 'FC-89F00320' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Arnica Tomar' WHERE sku = 'FC-127F5753' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Arnica Untar' WHERE sku = 'FC-25E452B6' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Bismuto Subnitrato' WHERE sku = 'FC-D037156B' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Borax Polvo' WHERE sku = 'FC-578F060C' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Espiritus Tomar' WHERE sku = 'FC-3676D5DC' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Espiritus Untar' WHERE sku = 'FC-62034164' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Flor De Arnica' WHERE sku = 'FC-5EF90195' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Glicerina' WHERE sku = 'FC-39036C88' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Haba Alcanforada' WHERE sku = 'FC-9507CD66' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Magnesia Anisada' WHERE sku = 'FC-CB5C11ED' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio óxido de zinc C/50' WHERE sku = 'FC-C4530823' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Pan Puerco' WHERE sku = 'FC-EFB599B5' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Perlas De Eter' WHERE sku = 'FC-FBD776D2' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Sulfatiazol' WHERE sku = 'FC-FD718DF3' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Sulfatiazol Polvo' WHERE sku = 'FC-47AAF23B' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Yodo Tomar' WHERE sku = 'FC-A680F97E' AND activo = true;
UPDATE public.productos SET nombre = 'Mercurio Yodo Untar' WHERE sku = 'FC-D3D28E20' AND activo = true;
UPDATE public.productos SET nombre = 'Mertiolate Kohn Rojo' WHERE sku = 'FC-926099D3' AND activo = true;
UPDATE public.productos SET nombre = 'Microdacyn lubricante cereza 50 ml' WHERE sku = 'FC-87932321' AND activo = true;
UPDATE public.productos SET nombre = 'Mousse Herbal Essences extra control' WHERE sku = 'FC-35168991' AND activo = true;
UPDATE public.productos SET nombre = 'Histiacil NF Infantil (Jarabe)' WHERE sku = 'FC-89794961' AND activo = true;
UPDATE public.productos SET nombre = 'Neo-Melubrina metamizol tabletas C/10' WHERE sku = 'FC-50002301' AND activo = true;
UPDATE public.productos SET nombre = 'Neurobión inyectable prellenado' WHERE sku = 'FC-82176351' AND activo = true;
UPDATE public.productos SET nombre = 'Nido leche en polvo (grande)' WHERE sku = 'FC-51067711' AND activo = true;
UPDATE public.productos SET nombre = 'Nido leche en polvo (bolsa)' WHERE sku = 'FC-59225411' AND activo = true;
UPDATE public.productos SET nombre = 'Nuvel desmaquillante bifásico oil' WHERE sku = 'FC-82790504' AND activo = true;
UPDATE public.productos SET nombre = 'Neo-Melubrina jarabe' WHERE sku = 'FC-50003151' AND activo = true;
UPDATE public.productos SET nombre = 'Palmolive jabón líquido cerezo y rosa' WHERE sku = 'FC-46657035' AND activo = true;
UPDATE public.productos SET nombre = 'Palmolive líquido neutro' WHERE sku = 'FC-46059556' AND activo = true;
UPDATE public.productos SET nombre = 'Pantene Control caída anticaída' WHERE sku = 'FC-01303454' AND activo = true;
UPDATE public.productos SET nombre = 'Ponds desmaquillante Bio-Hydra dual' WHERE sku = 'FC-56330378' AND activo = true;
UPDATE public.productos SET nombre = 'Protec termómetro digital' WHERE sku = 'FC-86708021' AND activo = true;
UPDATE public.productos SET nombre = 'Prudence chicle condones C/3' WHERE sku = 'FC-14985805' AND activo = true;
UPDATE public.productos SET nombre = 'Prudence condones C/3' WHERE sku = 'FC-49824911' AND activo = true;
UPDATE public.productos SET nombre = 'Prudence mora condones C/3' WHERE sku = 'FC-14980596' AND activo = true;
UPDATE public.productos SET nombre = 'Prudence Ultra Sensitive condones C/3' WHERE sku = 'FC-14985348' AND activo = true;
UPDATE public.productos SET nombre = 'Nuvel quita esmalte humectante lanolina' WHERE sku = 'FC-82740011' AND activo = true;
UPDATE public.productos SET nombre = 'Sonblefam S (Crema)' WHERE sku = 'FC-77FE5C83' AND activo = true;
UPDATE public.productos SET nombre = 'Clamoxin S (Amoxicilina/Clavulánico susp.)' WHERE sku = 'FC-0E0A9E42' AND activo = true;
UPDATE public.productos SET nombre = 'Senosiain supositorios adulto C/10' WHERE sku = 'FC-14704156' AND activo = true;
UPDATE public.productos SET nombre = 'Senosiain supositorios infantil C/10' WHERE sku = 'FC-14704163' AND activo = true;
UPDATE public.productos SET nombre = 'Shampoo Caprice biotina fuerza' WHERE sku = 'FC-46073040' AND activo = true;
UPDATE public.productos SET nombre = 'Shampoo Caprice natural manzana' WHERE sku = 'FC-46073156' AND activo = true;
UPDATE public.productos SET nombre = 'Shampoo Mennen lavanda extracto avena' WHERE sku = 'FC-46650708' AND activo = true;
UPDATE public.productos SET nombre = 'Shampoo Mennen miel manzana' WHERE sku = 'FC-46072050' AND activo = true;
UPDATE public.productos SET nombre = 'Shampoo Pantene bambú control caída' WHERE sku = 'FC-35155847' AND activo = true;
UPDATE public.productos SET nombre = 'Shampoo Pantene control caída' WHERE sku = 'FC-01303464' AND activo = true;
UPDATE public.productos SET nombre = 'Shampoo Savile bio sábila crecimiento resistente' WHERE sku = 'FC-06249226' AND activo = true;
UPDATE public.productos SET nombre = 'Shampoo Savile keratina sábila fuerza reparadora' WHERE sku = 'FC-06249240' AND activo = true;
UPDATE public.productos SET nombre = 'Softlub Extra condones C/3' WHERE sku = 'FC-49853867' AND activo = true;
UPDATE public.productos SET nombre = 'Sr. Ting pomada (ácido bórico)' WHERE sku = 'FC-23001331' AND activo = true;
UPDATE public.productos SET nombre = 'Syncol (Paracetamol)' WHERE sku = 'FC-79400556' AND activo = true;
UPDATE public.productos SET nombre = 'Syncol Max tabletas' WHERE sku = 'FC-34092301' AND activo = true;
UPDATE public.productos SET nombre = 'Tempra jarabe' WHERE sku = 'FC-50724298' AND activo = true;
UPDATE public.productos SET nombre = 'Toallas Saba Invisible con alas C/10' WHERE sku = 'FC-19006371' AND activo = true;
UPDATE public.productos SET nombre = 'Tukol-D jarabe' WHERE sku = 'FC-40010712' AND activo = true;
UPDATE public.productos SET nombre = 'Tukol-D jarabe infantil' WHERE sku = 'FC-00315021' AND activo = true;
UPDATE public.productos SET nombre = 'Vitacilina crema humectante' WHERE sku = 'FC-76000277' AND activo = true;
UPDATE public.productos SET nombre = 'XL-3 C/10' WHERE sku = 'FC-00525451' AND activo = true;
UPDATE public.productos SET nombre = 'XL-3 Xtra C/12' WHERE sku = 'FC-00170941' AND activo = true;
UPDATE public.productos SET concentracion = '150 ML', presentacion = '1 JARABE' WHERE sku = 'FC-89794961' AND activo = true AND concentracion ILIKE '%OPELLA%';

COMMIT;
